### PR TITLE
Fix Thor warning on orm type vs deault value

### PR DESCRIPTION
**Pull request by mfazekas**
Fixes: #13

### CODE REVIEW

**Comment by jasonfb** [comment]
thank you! I will take a look at this later

**Comment by mfazekas** [comment]
@jasonfb is there anything i can do to move this forward?
Shall i clean up travis.yml? It seems to be failing as some dependent gems doesn't support the old rubies now.

**Comment by jasonfb** [comment]
I'm gonna test this against Rails 4.2 and Rails 5 this weekend — then will pull in your PR. I'm having a little trouble with the Appraisal setup, but when I get that working will test a Rails 5 sample app against this code

**Comment by jasonfb** [comment]
@mfazekas --- sorry I'm so behind, but it's done now. This gem is now fully compatible with Rails 4.2 and Rails 5. Main README on https://github.com/jasonfb/nondestructive_migrations has been updated to indicate that you should use this gem versioned in lockstep with your Rails version

**Pull request merged**
